const photos = [
  {
    file: "berlin-train-station-night.jpg",
    title: "Waiting at the Station",
    alt: "A lone person sitting in a blue armchair on a Berlin railway station platform at night, with historic buildings and warm street lights beyond the tracks.",
    description: "A quiet night scene at a railway station in Berlin. A lone person sits in a blue armchair on the platform, surrounded by the architecture, tracks and warm street lights of the city.",
    caption: "",
    location: "Berlin, Germany",
    publishedAt: "2026-09-13T19:50:00+02:00",
    keywords: ["Berlin railway station","Berlin train station","Berlin night photography","Berlin street photography","Berlin urban photography","railway station photography","train station at night","candid photography Berlin","urban solitude","Berlin Germany","عکاسی برلین","ایستگاه قطار برلین","برلین در شب","عکاسی خیابانی برلین","عکاسی شهری برلین"],
    width: 1191,
    height: 1536
  },
  {
    file: "brussels-street-2024-final.jpg",
    title: "Walking Through Brussels",
    alt: "Three people walking along a cobblestone street in Brussels, Belgium, beside historic buildings and ornate street lamps.",
    description: "A candid street scene in Brussels, photographed in 2024. Three people walk along a narrow cobblestone street lined with historic buildings and ornate lamps, creating a quiet sense of movement through the city.",
    caption: "Brussels, 2024",
    location: "Brussels, Belgium",
    date: "2024",
    publishedAt: "2026-09-13T17:14:00+02:00",
    keywords: ["Brussels street photography","Brussels Belgium","Brussels architecture","Brussels old town","cobblestone street Brussels","candid photography Brussels","urban photography Belgium","Brussels city life","عکاسی بروکسل","خیابان های بروکسل","بروکسل بلژیک"],
    width: 657,
    height: 1536
  },
  {
    file: "brussels-atomium-2024.jpg",
    title: "Atomium, Brussels",
    alt: "The Atomium in Brussels rising above a tree-lined avenue, with its steel spheres reflecting the winter sky and a car on the road below.",
    description: "The Atomium in Brussels, photographed in 2024. The monumental steel structure rises above a tree-lined avenue, with its reflective spheres set against a pale winter sky and a lone car approaching along the road.",
    caption: "Brussels, 2024",
    location: "Atomium, Brussels, Belgium",
    date: "2024",
    publishedAt: "2026-09-13T16:09:00+02:00",
    keywords: ["Atomium Brussels","Brussels Atomium","Brussels Belgium","Atomium photography","Brussels architecture","Brussels landmark","Brussels street photography","Belgium photography","modern architecture Brussels","عکاسی بروکسل","اتمیوم بروکسل","بروکسل بلژیک","معماری بروکسل","عکاسی بلژیک"],
    width: 1086,
    height: 1448
  },
  {
    file: "berlin-reichstag-christmas-2024.jpg",
    title: "Reichstag at Night, Berlin",
    alt: "The Reichstag building in Berlin at night, illuminated through winter fog with German flags, a Christmas tree and people in the foreground.",
    description: "The Reichstag building in Berlin photographed at night in winter 2024. The illuminated glass dome and historic facade emerge through the mist, with German flags, a Christmas tree and visitors in the foreground.",
    caption: "Berlin, 2024",
    location: "Reichstag Building, Berlin, Germany",
    date: "2024",
    publishedAt: "2026-09-12T13:56:00+02:00",
    keywords: ["Reichstag Berlin","Reichstag at night","Reichstag dome","Berlin night photography","Berlin winter photography","Berlin Christmas","Berlin landmarks","German Bundestag","Reichstag building Germany","Berlin architecture photography","عکاسی برلین","رایشستاگ برلین","رایشستاگ در شب","گنبد رایشستاگ","عکاسی شب برلین","برلین آلمان"],
    width: 2475,
    height: 2258
  },
  {
    file: "bam-palm-grove-2023.jpg",
    title: "Bam Palm Grove",
    alt: "Three people carrying sheep through a palm grove in Bam, Iran, under a clear sky.",
    description: "Three people carrying sheep walk through a palm grove in Bam, Iran, photographed in 2023. Rows of date palms, bright daylight and figures moving through the cultivated landscape create a quiet documentary scene.",
    caption: "Bam, 2023",
    location: "Bam, Iran",
    date: "2023",
    publishedAt: "2026-09-09T02:38:00+02:00",
    keywords: ["Bam Iran","Bam palm grove","Bam date palms","Bam photography","Iran photography","Iranian landscape photography","documentary photography Iran","rural Iran","palm grove Iran","date palm photography","عکاسی بم","بم ایران","نخلستان بم","نخلستان","عکاسی ایران","روستایی ایران"],
    width: 1536,
    height: 1024
  },
  {
    file: "cottbus-ikmz-library-2023.jpg",
    title: "IKMZ Library, Cottbus",
    alt: "The curved glass facade of the IKMZ University Library in Cottbus, covered with a pattern of letters, seen above a snow-covered landscape.",
    description: "The IKMZ University Library in Cottbus, designed by Herzog & de Meuron, photographed in winter 2023. Its distinctive curved double-glass facade is covered with a pattern of letters and rises above the snow-covered grounds.",
    caption: "Cottbus, 2023",
    location: "IKMZ University Library, Cottbus, Germany",
    date: "2023",
    publishedAt: "2026-09-09T02:37:00+02:00",
    keywords: ["IKMZ Library Cottbus","University Library Cottbus","IKMZ Cottbus","BTU Cottbus library","Herzog & de Meuron Cottbus","Cottbus architecture","Cottbus photography","modern architecture Germany","curved glass architecture","winter Cottbus","عکاسی کوتبوس","کتابخانه دانشگاه کوتبوس","کتابخانه IKMZ","معماری مدرن آلمان","کوتبوس آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "prague-wenceslas-square-night-2023.jpg",
    title: "Wenceslas Square at Night",
    alt: "Wenceslas Square at night in Prague, with illuminated historic buildings, Christmas lights, a central monument and a bench in the foreground.",
    description: "Wenceslas Square at night in Prague, photographed in 2023. The illuminated historic buildings, festive trees and central monument form a symmetrical urban scene, with a rain-darkened square and bench in the foreground.",
    caption: "Prague, 2023",
    location: "Wenceslas Square, Prague, Czech Republic",
    date: "2023",
    publishedAt: "2026-09-08T17:54:01+02:00",
    keywords: ["Wenceslas Square Prague","Václavské náměstí","Wenceslas Square at night","Prague night photography","Prague Christmas lights","Prague city centre","Prague architecture","Prague photography","Czech Republic photography","عکاسی پراگ","میدان ونسسلاس پراگ","میدان واتسلاو پراگ","پراگ در شب","جمهوری چک"],
    width: 1086,
    height: 1630
  },
  {
    file: "prague-night-view-2023.jpg",
    title: "Prague at Night",
    alt: "Night view over Prague with illuminated historic buildings, the Vltava River and Charles Bridge seen from a hillside path.",
    description: "A night view across Prague, photographed in 2023. The illuminated historic cityscape and Vltava River unfold beyond a descending cobblestone path, framed by bare trees and warm street lights.",
    caption: "Prague, 2023",
    location: "Prague, Czech Republic",
    date: "2023",
    publishedAt: "2026-09-08T17:54:00+02:00",
    keywords: ["Prague at night","Prague night view","Prague skyline","Vltava River Prague","Charles Bridge Prague","Prague cityscape","Prague night photography","Prague photography","Czech Republic photography","عکاسی پراگ","پراگ در شب","نمای شبانه پراگ","رود ولتاوا","پل چارلز"],
    width: 896,
    height: 1195
  },
  {
    file: "nordhausen-fog-2022.jpg",
    title: "Foggy Street, Nordhausen",
    alt: "A fog-covered urban intersection in Nordhausen, Germany, with tram tracks, overhead wires, traffic lights and a Rossmann building fading into the mist.",
    description: "A foggy street scene in Nordhausen, photographed in 2022. Tram tracks, overhead wires and traffic lights disappear gradually into dense mist, creating a quiet and atmospheric urban landscape.",
    caption: "Nordhausen, 2022",
    location: "Nordhausen, Germany",
    date: "2022",
    publishedAt: "2026-09-08T15:55:00+02:00",
    keywords: ["Nordhausen fog","Nordhausen Germany photography","foggy street Nordhausen","Nordhausen tram","Nordhausen urban photography","fog photography Germany","misty city street","atmospheric urban photography","عکاسی نوردهاوزن","مه نوردهاوزن","خیابان مه آلود","نوردهاوزن آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "hamburg-speicherstadt-2022.jpg",
    title: "Hamburg Speicherstadt",
    alt: "Historic red-brick warehouse buildings lining a canal in Hamburg's Speicherstadt, with a bridge in the distance.",
    description: "A symmetrical view through Hamburg's historic Speicherstadt, photographed in 2022. Red-brick warehouse buildings line both sides of the canal, creating strong architectural perspective and leading lines toward the distant bridge.",
    caption: "Hamburg, 2022",
    location: "Speicherstadt, Hamburg, Germany",
    date: "2022",
    publishedAt: "2026-09-08T15:55:00+02:00",
    keywords: ["Hamburg Speicherstadt","Speicherstadt Hamburg","Hamburg canal","Hamburg warehouse district","Hamburg architecture","Hamburg photography","Speicherstadt photography","UNESCO Hamburg","red brick architecture","Germany photography","عکاسی هامبورگ","اشپایشرشتات هامبورگ","کانال هامبورگ","معماری هامبورگ","هامبورگ آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "berlin-victory-column-2022.jpg",
    title: "Berlin Victory Column",
    alt: "The Berlin Victory Column with the gilded Victoria statue viewed from a broad staircase between stone walls under a clear sky.",
    description: "The Berlin Victory Column (Siegessäule), photographed from the entrance staircase in Berlin in 2022. The symmetrical staircase and surrounding stone walls lead the eye toward the column and its gilded Victoria statue.",
    caption: "Berlin, 2022",
    location: "Berlin, Germany",
    date: "2022",
    publishedAt: "2026-09-08T03:18:00+02:00",
    keywords: ["Berlin Victory Column","Siegessäule Berlin","Goldelse Berlin","Victory Column Germany","Berlin landmark","Berlin monument","Berlin photography","Berlin architecture photography","Tiergarten Berlin","Germany photography","عکاسی برلین","ستون پیروزی برلین","زیگس زویله برلین","برلین آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "cologne-cathedral-2022.jpg",
    title: "Cologne Cathedral and Equestrian Monument",
    alt: "Cologne Cathedral rises behind a bronze equestrian monument, with orange trains crossing the railway tracks in the foreground under an overcast sky.",
    description: "Cologne Cathedral and an equestrian monument near the Hohenzollern Bridge, photographed in Cologne in 2022. Orange trains pass through the foreground, contrasting with the Gothic cathedral and historic monument.",
    caption: "Cologne, 2022",
    location: "Cologne, Germany",
    date: "2022",
    publishedAt: "2026-09-08T00:28:00+02:00",
    keywords: ["Cologne Cathedral","Kölner Dom","Cologne Germany photography","Cologne photography","Hohenzollern Bridge","equestrian monument Cologne","Cologne train photography","urban photography Cologne","Gothic architecture Cologne","عکاسی کلن","کلیسای جامع کلن","کلن آلمان","پل هوهنزولرن"],
    width: 1024,
    height: 1536
  },
  {
    file: "autumn-tree-frankfurt-2022.jpg",
    title: "Autumn Tree, Frankfurt",
    alt: "A large autumn tree with rust-coloured leaves beside a park path and pond in Frankfurt, Germany, with two people walking beneath it.",
    description: "An autumn scene in Frankfurt, photographed in 2022. A large tree with dense rust-coloured foliage dominates the frame, while two people walk along a quiet path beside the water.",
    caption: "Frankfurt, 2022",
    location: "Frankfurt, Germany",
    date: "2022",
    publishedAt: "2026-09-07T22:18:43+02:00",
    keywords: ["Frankfurt autumn","Frankfurt Germany photography","autumn tree Frankfurt","Frankfurt park","Frankfurt nature photography","autumn photography Germany","fall foliage Frankfurt","urban nature Frankfurt","عکاسی فرانکفورت","پاییز فرانکفورت","درخت پاییزی","فرانکفورت آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "hafez-goethe-monument-weimar-2022.jpg",
    title: "Hafez–Goethe Monument, Weimar",
    alt: "Two monumental granite chairs facing each other at the Hafez–Goethe Monument in Weimar, Germany, surrounded by autumn trees and a historic white building.",
    description: "The Hafez–Goethe Monument on Beethovenplatz in Weimar, photographed in autumn 2022. Two monumental granite chairs face one another, symbolising the imagined dialogue between the Persian poet Hafez and the German poet Johann Wolfgang von Goethe.",
    caption: "HAFEZ-Goethe\nWeimar, 2022",
    location: "Weimar, Germany",
    date: "2022",
    publishedAt: "2026-09-07T17:12:35+02:00",
    keywords: ["Hafez-Goethe Monument","Hafis-Goethe-Denkmal","Hafez Goethe Weimar","Hafez monument Weimar","Goethe monument Weimar","Beethovenplatz Weimar","Weimar Germany photography","Hafez photography","Persian poetry in Germany","Goethe and Hafez","East-West cultural dialogue","عکاسی وایمار","بنای حافظ گوته","حافظ و گوته","وایمار آلمان"],
    width: 1536,
    height: 1024
  }
];
