const photos = [
  {
    file: "magere-brug-amsterdam-2024.jpg",
    title: "Magere Brug, Amsterdam",
    alt: "The illuminated Magere Brug over the Amstel in Amsterdam, Netherlands, at blue hour, with boats on the river and city buildings beyond.",
    description: "The illuminated Magere Brug over the Amstel in Amsterdam, photographed at blue hour in 2024. Boats move across the river while the bridge lights reflect on the water and the city fades into the evening beyond.",
    caption: "Amsterdam, 2024",
    location: "Magere Brug, Amsterdam, Netherlands",
    date: "2024",
    publishedAt: "2026-09-14T23:23:00+02:00",
    keywords: ["Magere Brug","Skinny Bridge","Amstel River","Amsterdam","Amsterdam photography","Amsterdam night photography","Amsterdam bridge","Amsterdam cityscape","Netherlands photography","blue hour Amsterdam","Amsterdam lights","عکاسی آمستردام","پل ماگره بروگ","پل لاغر آمستردام","رود آمستل","آمستردام در شب"],
    width: 1536,
    height: 1152
  },
  {
    file: "rijksmuseum-sculpture-amsterdam-2024.jpg",
    title: "Sculpture, Rijksmuseum, Amsterdam",
    alt: "A historic sculpture displayed at the Rijksmuseum in Amsterdam, Netherlands.",
    description: "A historic sculpture photographed inside the Rijksmuseum in Amsterdam, Netherlands, in 2024.",
    caption: "",
    location: "Rijksmuseum, Amsterdam, Netherlands",
    date: "2024",
    publishedAt: "2026-09-14T22:01:00+02:00",
    keywords: ["Rijksmuseum","Rijksmuseum Amsterdam","Amsterdam museum","historic sculpture","sculpture photography","Amsterdam photography","Netherlands photography","museum photography","عکاسی آمستردام","موزه ملی آمستردام","مجسمه","مجسمه تاریخی","عکاسی موزه"],
    width: 1349,
    height: 1536
  },
  {
    file: "rijksmuseum-crucifix-amsterdam-2024.jpg",
    title: "Crucifix, Rijksmuseum, Amsterdam",
    alt: "A historic crucifix sculpture displayed at the Rijksmuseum in Amsterdam, Netherlands.",
    description: "A historic crucifix sculpture photographed inside the Rijksmuseum in Amsterdam, Netherlands, in 2024.",
    caption: "",
    location: "Rijksmuseum, Amsterdam, Netherlands",
    date: "2024",
    publishedAt: "2026-09-14T22:00:00+02:00",
    keywords: ["Rijksmuseum","Rijksmuseum Amsterdam","Amsterdam museum","crucifix","religious sculpture","Amsterdam photography","Netherlands photography","museum photography","عکاسی آمستردام","موزه ملی آمستردام","صلیب مصلوب","مجسمه مذهبی","عکاسی موزه"],
    width: 1152,
    height: 1536
  },
  {
    file: "amsterdam-no-public-peeing.jpg",
    title: "No Public Peeing, Amsterdam",
    alt: "Amsterdam municipal signs warning that public peeing is illegal, with a €140 fine, mounted on a street pole in Amsterdam, Netherlands.",
    description: "A street photograph in Amsterdam showing municipal signs in Dutch and English warning that public peeing is illegal and carries a €140 fine. The signs carry the Gemeente Amsterdam and How to Amsterdam branding.",
    caption: "",
    location: "Amsterdam, Netherlands",
    date: "2024",
    publishedAt: "2026-09-14T19:39:00+02:00",
    keywords: ["Amsterdam","Amsterdam street photography","Amsterdam municipal signs","public urination Amsterdam","Gemeente Amsterdam","How to Amsterdam","Amsterdam urban photography","Amsterdam documentary photography","Netherlands photography","عکاسی آمستردام","آمستردام","تابلوهای آمستردام","عکاسی خیابانی آمستردام","عکاسی شهری آمستردام","هلند"],
    width: 1080,
    height: 1536
  },
  {
    file: "parisi-udvar-budapest-2024.jpg",
    title: "Párisi Udvar, Budapest",
    alt: "Párisi Udvar in Budapest, Hungary, with its ornate historic facade, tower and street scene under a blue sky.",
    description: "Párisi Udvar in Budapest, photographed in 2024. The ornate historic facade and distinctive tower rise above the city street, with parked cars and the wooded Buda hills visible beyond.",
    caption: "Budapest, 2024",
    location: "Párisi Udvar, Ferenciek tere 10, Budapest, Hungary",
    date: "2024",
    publishedAt: "2026-09-14T17:47:52+02:00",
    keywords: ["Párisi Udvar","Parisian Court Budapest","Párisi Udvar Budapest","Párisi Udvar Hotel Budapest","Ferenciek tere","Budapest architecture","Budapest photography","Budapest Hungary","historic architecture Budapest","Art Nouveau Budapest","Budapest city photography","عکاسی بوداپست","پاریسی اودوار","پاریسی اودوار بوداپست","پاریسین کورت بوداپست","معماری بوداپست","بوداپست مجارستان","فرنچیک تر بوداپست"],
    width: 1086,
    height: 1448
  },
  {
    file: "budapest-2024.jpg",
    title: "Buda Castle Funicular, Budapest",
    alt: "The Buda Castle Funicular descending toward the Danube in Budapest, Hungary, with the Chain Bridge, river and city skyline beyond under a dramatic cloud-filled sky.",
    description: "A view over Budapest from the Buda Castle Funicular, photographed in 2024. The historic railway descends toward the Danube, while the Chain Bridge, river and city skyline unfold beneath a dramatic sky.",
    caption: "Budapest, 2024",
    location: "Buda Castle Funicular, Budapest, Hungary",
    date: "2024",
    publishedAt: "2026-09-14T17:10:00+02:00",
    keywords: ["Buda Castle Funicular","Budapest Funicular","Budavári Sikló","Budapest Hungary","Budapest photography","Budapest cityscape","Budapest skyline","Chain Bridge Budapest","Budapest Danube","Buda Castle District","Budapest travel photography","عکاسی بوداپست","بوداپست مجارستان","فونیکولار بوداپست","فونی کولار قلعه بودا","پل زنجیری بوداپست","دانوب بوداپست","قلعه بودا","عکاسی مجارستان"],
    width: 1178,
    height: 2013
  },
  {
    file: "vienna-crow.jpg",
    title: "Crow, Vienna",
    alt: "A black crow perched on a white railing in Vienna, Austria, with dense green trees in the background.",
    description: "A black crow perched on a white railing in Vienna, photographed against a dense green backdrop of trees. The close framing and direct gaze create a quiet, watchful urban nature portrait.",
    caption: "",
    location: "Vienna, Austria",
    publishedAt: "2026-09-14T13:03:00+02:00",
    keywords: ["crow Vienna","Vienna crow","crow photography Vienna","Vienna Austria","Vienna wildlife photography","urban wildlife Vienna","bird photography Vienna","black crow","Vienna nature photography","عکاسی وین","کلاغ وین","کلاغ","حیات وحش شهری وین","عکاسی پرنده وین","وین اتریش"],
    width: 1152,
    height: 1536
  },
  {
    file: "vienna-gloriette-2024.jpg",
    title: "Gloriette, Vienna",
    alt: "The Gloriette at Schönbrunn Palace in Vienna, Austria, viewed from the palace gardens with its central fountain and visitors in the foreground.",
    description: "The Gloriette at Schönbrunn Palace in Vienna, photographed in 2024. The monumental arcade rises above the formal gardens and central fountain, with visitors crossing the broad gravel path in the foreground.",
    caption: "Vienna, 2024",
    location: "Schönbrunn Palace, Vienna, Austria",
    date: "2024",
    publishedAt: "2026-09-14T04:21:00+02:00",
    keywords: ["Gloriette Vienna","Schönbrunn Palace","Schönbrunn Vienna","Vienna photography","Vienna Austria","Gloriette photography","Schönbrunn gardens","Vienna architecture","Austria photography","عکاسی وین","گِلوریت وین","کاخ شون‌برون","شون‌برون وین","وین اتریش","عکاسی اتریش"],
    width: 1173,
    height: 1536
  },
  {
    file: "munich-eisbach-surfers-2024.jpg",
    title: "Eisbach Surfers, Munich",
    alt: "A surfer in a wetsuit riding a board in the fast-flowing Eisbach in Munich, with surfboards behind a fence and a German warning sign reading ‘Lebensgefahr’.",
    description: "A documentary photograph of the Eisbach in Munich, photographed in 2024. A surfer moves through the fast-flowing river behind a fence, while surfboards and a prominent ‘Lebensgefahr’ warning sign create a striking contrast between recreation and danger.",
    caption: "Munich, 2024",
    location: "Eisbachwelle, Munich, Germany",
    date: "2024",
    publishedAt: "2026-09-14T00:15:00+02:00",
    keywords: ["Eisbach surfers Munich","Eisbachwelle","Munich surfing","Munich street photography","Munich documentary photography","Munich Germany","Lebensgefahr","Eisbach wave","surfing Germany","عکاسی مونیخ","موج سواری مونیخ","ایس باخ مونیخ","عکاسی خیابانی مونیخ","مونیخ آلمان"],
    width: 1178,
    height: 1335
  },
  {
    file: "berlin-vintage-volkswagen-2024.jpg",
    title: "Vintage Volkswagen, Berlin",
    alt: "A vintage Volkswagen van parked on a Berlin street beneath trees, with political campaign posters visible behind it.",
    description: "A vintage Volkswagen van parked on a Berlin street, photographed in 2024. The pale vehicle is framed by trees and urban shadows, while political campaign posters behind it add a distinctly contemporary Berlin context to the classic vehicle.",
    caption: "Berlin, 2024",
    location: "Berlin, Germany",
    date: "2024",
    publishedAt: "2026-09-14T00:14:00+02:00",
    keywords: ["vintage Volkswagen Berlin","Volkswagen van Berlin","Volkswagen bus Berlin","Berlin street photography","Berlin documentary photography","Berlin urban photography","classic Volkswagen Germany","vintage car Berlin","Berlin Germany","German street photography","عکاسی برلین","فولکس واگن قدیمی برلین","ون فولکس واگن برلین","ماشین قدیمی برلین","عکاسی خیابانی برلین","برلین آلمان"],
    width: 1248,
    height: 1536
  },
  {
    file: "berlin-train-station-night.jpg",
    title: "Waiting at the Station",
    alt: "A lone person sitting in a blue armchair on a Berlin railway station platform at night, with historic buildings and warm street lights beyond the tracks.",
    description: "A quiet night scene at a railway station in Berlin. A lone person sits in a blue armchair on the platform, surrounded by the architecture, tracks and warm street lights of the city.",
    caption: "",
    location: "Berlin, Germany",
    publishedAt: "2026-09-13T19:50:00+02:00",
    keywords: ["Berlin railway station","Berlin train station","Berlin night photography","Berlin street photography","Berlin urban photography","railway station photography","train station at night","candid photography Berlin","urban solitude","Berlin Germany","عکاسی برلین","ایستگاه قطار برلین","برلین در شب","عکاسی خیابانی برلین","عکاسی شهری برلین"],
    width: 1191,
    height: 1536
  },
  {
    file: "brussels-street-2024-final.jpg",
    title: "Walking Through Brussels",
    alt: "Three people walking along a cobblestone street in Brussels, Belgium, beside historic buildings and ornate street lamps.",
    description: "A candid street scene in Brussels, photographed in 2024. Three people walk along a narrow cobblestone street lined with historic buildings and ornate lamps, creating a quiet sense of movement through the city.",
    caption: "Brussels, 2024",
    location: "Brussels, Belgium",
    date: "2024",
    publishedAt: "2026-09-13T17:14:00+02:00",
    keywords: ["Brussels street photography","Brussels Belgium","Brussels architecture","Brussels old town","cobblestone street Brussels","candid photography Brussels","urban photography Belgium","Brussels city life","عکاسی بروکسل","خیابان های بروکسل","بروکسل بلژیک"],
    width: 657,
    height: 1536
  },
  {
    file: "brussels-atomium-2024.jpg",
    title: "Atomium, Brussels",
    alt: "The Atomium in Brussels rising above a tree-lined avenue, with its steel spheres reflecting the winter sky and a car on the road below.",
    description: "The Atomium in Brussels, photographed in 2024. The monumental steel structure rises above a tree-lined avenue, with its reflective spheres set against a pale winter sky and a lone car approaching along the road.",
    caption: "Brussels, 2024",
    location: "Atomium, Brussels, Belgium",
    date: "2024",
    publishedAt: "2026-09-13T16:09:00+02:00",
    keywords: ["Atomium Brussels","Brussels Atomium","Brussels Belgium","Atomium photography","Brussels architecture","Brussels landmark","Brussels street photography","Belgium photography","modern architecture Brussels","عکاسی بروکسل","اتمیوم بروکسل","بروکسل بلژیک","معماری بروکسل","عکاسی بلژیک"],
    width: 1086,
    height: 1448
  },
  {
    file: "berlin-reichstag-christmas-2024.jpg",
    title: "Reichstag at Night, Berlin",
    alt: "The Reichstag building in Berlin at night, illuminated through winter fog with German flags, a Christmas tree and people in the foreground.",
    description: "The Reichstag building in Berlin photographed at night in winter 2024. The illuminated glass dome and historic facade emerge through the mist, with German flags, a Christmas tree and visitors in the foreground.",
    caption: "Berlin, 2024",
    location: "Reichstag Building, Berlin, Germany",
    date: "2024",
    publishedAt: "2026-09-12T13:56:00+02:00",
    keywords: ["Reichstag Berlin","Reichstag at night","Reichstag dome","Berlin night photography","Berlin winter photography","Berlin Christmas","Berlin landmarks","German Bundestag","Reichstag building Germany","Berlin architecture photography","عکاسی برلین","رایشستاگ برلین","رایشستاگ در شب","گنبد رایشستاگ","عکاسی شب برلین","برلین آلمان"],
    width: 2475,
    height: 2258
  },
  {
    file: "bam-palm-grove-2023.jpg",
    title: "Bam Palm Grove",
    alt: "Three people carrying sheep through a palm grove in Bam, Iran, under a clear sky.",
    description: "Three people carrying sheep walk through a palm grove in Bam, Iran, photographed in 2023. Rows of date palms, bright daylight and figures moving through the cultivated landscape create a quiet documentary scene.",
    caption: "Bam, 2023",
    location: "Bam, Iran",
    date: "2023",
    publishedAt: "2026-09-09T02:38:00+02:00",
    keywords: ["Bam Iran","Bam palm grove","Bam date palms","Bam photography","Iran photography","Iranian landscape photography","documentary photography Iran","rural Iran","palm grove Iran","date palm photography","عکاسی بم","بم ایران","نخلستان بم","نخلستان","عکاسی ایران","روستایی ایران"],
    width: 1536,
    height: 1024
  },
  {
    file: "cottbus-ikmz-library-2023.jpg",
    title: "IKMZ Library, Cottbus",
    alt: "The curved glass facade of the IKMZ University Library in Cottbus, covered with a pattern of letters, seen above a snow-covered landscape.",
    description: "The IKMZ University Library in Cottbus, designed by Herzog & de Meuron, photographed in winter 2023. Its distinctive curved double-glass facade is covered with a pattern of letters and rises above the snow-covered grounds.",
    caption: "Cottbus, 2023",
    location: "IKMZ University Library, Cottbus, Germany",
    date: "2023",
    publishedAt: "2026-09-09T02:37:00+02:00",
    keywords: ["IKMZ Library Cottbus","University Library Cottbus","IKMZ Cottbus","BTU Cottbus library","Herzog & de Meuron Cottbus","Cottbus architecture","Cottbus photography","modern architecture Germany","curved glass architecture","winter Cottbus","عکاسی کوتبوس","کتابخانه دانشگاه کوتبوس","کتابخانه IKMZ","معماری مدرن آلمان","کوتبوس آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "prague-wenceslas-square-night-2023.jpg",
    title: "Wenceslas Square at Night",
    alt: "Wenceslas Square at night in Prague, with illuminated historic buildings, Christmas lights, a central monument and a bench in the foreground.",
    description: "Wenceslas Square at night in Prague, photographed in 2023. The illuminated historic buildings, festive trees and central monument form a symmetrical urban scene, with a rain-darkened square and bench in the foreground.",
    caption: "Prague, 2023",
    location: "Wenceslas Square, Prague, Czech Republic",
    date: "2023",
    publishedAt: "2026-09-08T17:54:01+02:00",
    keywords: ["Wenceslas Square Prague","Václavské náměstí","Wenceslas Square at night","Prague night photography","Prague Christmas lights","Prague city centre","Prague architecture","Prague photography","Czech Republic photography","عکاسی پراگ","میدان ونسسلاس پراگ","میدان واتسلاو پراگ","پراگ در شب","جمهوری چک"],
    width: 1086,
    height: 1630
  },
  {
    file: "prague-night-view-2023.jpg",
    title: "Prague at Night",
    alt: "Night view over Prague with illuminated historic buildings, the Vltava River and Charles Bridge seen from a hillside path.",
    description: "A night view across Prague, photographed in 2023. The illuminated historic cityscape and Vltava River unfold beyond a descending cobblestone path, framed by bare trees and warm street lights.",
    caption: "Prague, 2023",
    location: "Prague, Czech Republic",
    date: "2023",
    publishedAt: "2026-09-08T17:54:00+02:00",
    keywords: ["Prague at night","Prague night view","Prague skyline","Vltava River Prague","Charles Bridge Prague","Prague cityscape","Prague night photography","Prague photography","Czech Republic photography","عکاسی پراگ","پراگ در شب","نمای شبانه پراگ","رود ولتاوا","پل چارلز"],
    width: 896,
    height: 1195
  },
  {
    file: "nordhausen-fog-2022.jpg",
    title: "Foggy Street, Nordhausen",
    alt: "A fog-covered urban intersection in Nordhausen, Germany, with tram tracks, overhead wires, traffic lights and a Rossmann building fading into the mist.",
    description: "A foggy street scene in Nordhausen, photographed in 2022. Tram tracks, overhead wires and traffic lights disappear gradually into dense mist, creating a quiet and atmospheric urban landscape.",
    caption: "Nordhausen, 2022",
    location: "Nordhausen, Germany",
    date: "2022",
    publishedAt: "2026-09-08T15:55:00+02:00",
    keywords: ["Nordhausen fog","Nordhausen Germany photography","foggy street Nordhausen","Nordhausen tram","Nordhausen urban photography","fog photography Germany","misty city street","atmospheric urban photography","عکاسی نوردهاوزن","مه نوردهاوزن","خیابان مه آلود","نوردهاوزن آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "hamburg-speicherstadt-2022.jpg",
    title: "Hamburg Speicherstadt",
    alt: "Historic red-brick warehouse buildings lining a canal in Hamburg's Speicherstadt, with a bridge in the distance.",
    description: "A symmetrical view through Hamburg's historic Speicherstadt, photographed in 2022. Red-brick warehouse buildings line both sides of the canal, creating strong architectural perspective and leading lines toward the distant bridge.",
    caption: "Hamburg, 2022",
    location: "Speicherstadt, Hamburg, Germany",
    date: "2022",
    publishedAt: "2026-09-08T15:55:00+02:00",
    keywords: ["Hamburg Speicherstadt","Speicherstadt Hamburg","Hamburg canal","Hamburg warehouse district","Hamburg architecture","Hamburg photography","Speicherstadt photography","UNESCO Hamburg","red brick architecture","Germany photography","عکاسی هامبورگ","اشپایشرشتات هامبورگ","کانال هامبورگ","معماری هامبورگ"],
    width: 1024,
    height: 1536
  },
  {
    file: "berlin-victory-column-2022.jpg",
    title: "Berlin Victory Column",
    alt: "Berlin's Victory Column rising above the trees at Großer Stern, with its gilded statue of Victoria against the sky.",
    description: "The Berlin Victory Column at Großer Stern, photographed in 2022. The monumental column and gilded Victoria rise above the surrounding trees in the Tiergarten.",
    caption: "Berlin, 2022",
    location: "Victory Column, Berlin, Germany",
    date: "2022",
    publishedAt: "2026-09-08T03:18:00+02:00",
    keywords: ["Berlin Victory Column","Siegessäule Berlin","Großer Stern","Berlin landmark","Berlin architecture","Berlin photography","Tiergarten Berlin","Victoria statue Berlin","عکاسی برلین","ستون پیروزی برلین","زیگس‌زویله","برلین آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "cologne-cathedral-2022.jpg",
    title: "Cologne Cathedral and Equestrian Monument",
    alt: "Cologne Cathedral and a historic equestrian monument in Cologne, Germany, viewed against the city skyline.",
    description: "A view of Cologne Cathedral and a historic equestrian monument in Cologne, photographed in 2022.",
    caption: "Cologne, 2022",
    location: "Cologne, Germany",
    date: "2022",
    publishedAt: "2026-09-08T00:28:00+02:00",
    keywords: ["Cologne Cathedral","Kölner Dom","Cologne Germany","Cologne photography","Cologne skyline","equestrian monument Cologne","Germany photography","عکاسی کلن","کلیسای جامع کلن","کلن آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "autumn-tree-frankfurt-2022.jpg",
    title: "Autumn Tree, Frankfurt",
    alt: "A large autumn tree with rust-coloured leaves beside a park path and pond in Frankfurt, Germany, with two people walking beneath it.",
    description: "An autumn scene in Frankfurt, photographed in 2022. A large tree with dense rust-coloured foliage dominates the frame, while two people walk along a quiet path beside the water.",
    caption: "Frankfurt, 2022",
    location: "Frankfurt, Germany",
    date: "2022",
    publishedAt: "2026-09-07T22:18:43+02:00",
    keywords: ["Autumn Frankfurt","Frankfurt Germany","Frankfurt photography","autumn photography Germany","Frankfurt park","tree photography","Frankfurt nature","عکاسی فرانکفورت","پاییز فرانکفورت","فرانکفورت آلمان"],
    width: 1024,
    height: 1536
  },
  {
    file: "hafez-goethe-monument-weimar-2022.jpg",
    title: "Hafez–Goethe Monument, Weimar",
    alt: "Two monumental granite chairs facing each other at the Hafez–Goethe Monument in Weimar, Germany, surrounded by autumn trees and a historic white building.",
    description: "The Hafez–Goethe Monument on Beethovenplatz in Weimar, photographed in autumn 2022. Two monumental granite chairs face one another, symbolising the imagined dialogue between the Persian poet Hafez and the German poet Johann Wolfgang von Goethe.",
    caption: "HAFEZ-Goethe\nWeimar, 2022",
    location: "Weimar, Germany",
    date: "2022",
    publishedAt: "2026-09-07T17:12:35+02:00",
    keywords: ["Hafez-Goethe Monument","Hafis-Goethe-Denkmal","Hafez Goethe Weimar","Hafez monument Weimar","Goethe monument Weimar","Beethovenplatz Weimar","Weimar Germany photography","Hafez photography","Persian poetry in Germany","Goethe and Hafez","East-West cultural dialogue","عکاسی وایمار","بنای حافظ گوته","حافظ و گوته","وایمار آلمان"],
    width: 1536,
    height: 1024
  }
];